[package]
name = "flashbots-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers-flashbots = { git = "https://github.com/tanishqjasoria/ethers-flashbots" }